# Generated by Django 5.1.2 on 2024-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ds', models.TextField(max_length=200)),
            ],
        ),
    ]
