# Generated by Django 5.1.2 on 2024-12-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='cat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
