# Generated by Django 5.1.2 on 2024-12-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='ds',
            field=models.TextField(max_length=2000),
        ),
    ]
